import type { NextPage } from "next";
import Head from "next/head";
import { motion } from "framer-motion";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Powered By Buttertoast</title>
        <meta
          name="description"
          content="Generated by create next app, Buttertoast boilerplate"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.main
        initial={{
          opacity: 0,
        }}
        animate={{
          opacity: 1,
          transition: {
            duration: 2,
            delay: 1,
          },
        }}
        className="grid place-items-center h-screen"
      >
        <div className="flex flex-col gap-y-6 items-center">
          <h1 className="text-6xl mb-16">
            Buttertoast Base Setup with HTTP & Redux Ready
          </h1>
          <h2 className="text-4xl mb-4">Powered by</h2>
          <ul>
            <li>Next js</li>
            <li>Tailwind CSS</li>
            <li>Sass</li>
            <li>Framer Motion</li>
            <li>DaisyUI</li>
            <li>Axios</li>
            <li>Redux</li>
          </ul>
        </div>
      </motion.main>
    </>
  );
};

export default Home;
